#include <structures/AdvancedWindTrap.h>

#include <globals.h>

#include <FileClasses/GFXManager.h>
#include <House.h>
#include <Game.h>
#include <ScreenBorder.h>
#include <mmath.h>

#include <GUI/ObjectInterfaces/WindTrapInterface.h>

AdvancedWindTrap::AdvancedWindTrap(House* newOwner) : StructureBase(newOwner) {
    AdvancedWindTrap::init();

    setHealth(getMaxHealth());
}

AdvancedWindTrap::AdvancedWindTrap(InputStream& stream) : StructureBase(stream) {
    AdvancedWindTrap::init();
}

void AdvancedWindTrap::init() {
    itemID = Structure_AdvancedWindTrap;
    owner->incrementStructures(itemID);

    structureSize.x = 3;
    structureSize.y = 3;

    graphicID = ObjPic_AdvancedWindTrap;
    graphic = pGFXManager->getObjPic(graphicID, getOwner()->getHouseID());
    // The AdvancedWindTrap sprite atlas has 8 frames in a single row (48×48 each).
    // Do NOT copy WindTrap's synthetic animation parameters — those only apply to
    // the 320×224 texture generated by generateWindtrapAnimationFrames().
    numImagesX = 8;
    numImagesY = 1;
    firstAnimFrame = 0;
    lastAnimFrame = 7;
}

AdvancedWindTrap::~AdvancedWindTrap() = default;

bool AdvancedWindTrap::update() {
    bool bResult = StructureBase::update();

    if(bResult) {
        if(justPlacedTimer <= 0 || curAnimFrame != 0) {
            curAnimFrame = (currentGame->getGameCycleCount()/8) % 8;
        }

        auto* citySim = currentGame->getCitySimulation();
        if (citySim) {
            citySim->registerPowerSource(location.x, location.y, getProducedPower());
        }
    }

    return bResult;
}

void AdvancedWindTrap::blitToScreen() {
    // Draw the building body (animated power-plant atlas) first.
    StructureBase::blitToScreen();

    // Like the Starport and Palace, the Advanced Windtrap flies two animated
    // house-colored flags at the top corners of its 3x3 footprint. Reuse the
    // ObjPic_CornerFlag sprite (3 frames) and the same ~8-cycle timing as the
    // map corner flags in Game::drawCornerFlags().
    if(fogged) {
        return;
    }

    SDL_Texture* flagTex = pGFXManager->getZoomedObjPic(ObjPic_CornerFlag, getOwner()->getHouseID(), currentZoomlevel);
    if(flagTex == nullptr) {
        return;
    }

    const int zoomedTileSize = world2zoomedWorld(TILESIZE);
    const int frame = (currentGame->getGameCycleCount() / 8) % 3;

    const int screenX = screenborder->world2screenX(lround(realX));
    const int screenY = screenborder->world2screenY(lround(realY));
    const int buildingW = zoomedTileSize * structureSize.x;

    SDL_Rect src = { frame * zoomedTileSize, 0, zoomedTileSize, zoomedTileSize };

    // Raise both flags one tile above the roofline so the poles rise off the top.
    const int flagY = screenY - zoomedTileSize;

    SDL_Rect leftDst  = { screenX, flagY, zoomedTileSize, zoomedTileSize };
    SDL_RenderCopy(renderer, flagTex, &src, &leftDst);

    SDL_Rect rightDst = { screenX + buildingW - zoomedTileSize, flagY, zoomedTileSize, zoomedTileSize };
    SDL_RenderCopy(renderer, flagTex, &src, &rightDst);
}

void AdvancedWindTrap::setHealth(FixPoint newHealth) {
    int producedPowerBefore = getProducedPower();
    StructureBase::setHealth(newHealth);
    int producedPowerAfterwards = getProducedPower();

    owner->setProducedPower(owner->getProducedPower() - producedPowerBefore + producedPowerAfterwards);
}

ObjectInterface* AdvancedWindTrap::getInterfaceContainer() {
    if((pLocalHouse == owner) || (debug == true)) {
        return WindTrapInterface::create(objectID);
    } else {
        return DefaultObjectInterface::create(objectID);
    }
}

int AdvancedWindTrap::getProducedPower() const {
    int nominal = abs(currentGame->objectData.data[Structure_AdvancedWindTrap][originalHouseID].power);
    FixPoint ratio = getHealth() / getMaxHealth();
    return lround(ratio * nominal);
}
