.TH "dunecity" "6" "0.99.5" "DuneCity Team" ""
.SH "NAME"
A Dune II reimplementation with city simulation.
.br
.SH "SYNTAX"
dunecity [--showlog] [--fullscreen|--window] [--PlayerName=X] [--ServerPort=X]
.br
.SH "DESCRIPTION"
Lead one of three interplanetary houses, Atreides, Harkonnen or Ordos, in an attempt to harvest the largest amount of spice from the sand dunes. Exchange your spice stockpiles for credits through refinement and build an army capable of thwarting attempts of the other houses to stop your harvesting!
.br

DuneCity is a fork of Dune Legacy that integrates Micropolis-style city simulation into the classic Dune II RTS gameplay. Build zones, manage power grids, collect taxes, and grow your city while commanding military forces.
.br

NOTE: Original Dune 2 game files are needed. Copy all PAK files to ~/.config/dunecity/data/
.br
.SH "SEE ALSO"
Web: https://github.com/stefanvanderwel/dunecity
.br
