// DuneCity direct transport. P2PKit 94ae7eb8818a629478e0a6ba0aa3232c5fc0b1ab (MIT); local security patches. Generated by tools/p2pkit-build/build.mjs.
(() => {
  var __defProp = Object.defineProperty;
  var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
  var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

  // platform/web/p2pkit/src/utils/emitter.ts
  var Emitter = class {
    constructor() {
      __publicField(this, "handlers", {});
    }
    /** Subscribe to `event`. Returns an unsubscribe function. */
    on(event, handler) {
      var _a;
      ;
      ((_a = this.handlers)[event] ?? (_a[event] = /* @__PURE__ */ new Set())).add(handler);
      return () => this.off(event, handler);
    }
    /** Subscribe once; the handler is removed after its first invocation. */
    once(event, handler) {
      const wrap = ((...args) => {
        this.off(event, wrap);
        handler(...args);
      });
      return this.on(event, wrap);
    }
    /** Remove a previously registered handler. */
    off(event, handler) {
      this.handlers[event]?.delete(handler);
    }
    /** Synchronously invoke every handler registered for `event`. */
    emit(event, ...args) {
      const set = this.handlers[event];
      if (!set) return;
      for (const handler of [...set]) handler(...args);
    }
    /** Remove all handlers for one event, or all events when `event` is omitted. */
    removeAll(event) {
      if (event !== void 0) this.handlers[event]?.clear();
      else for (const key of Object.keys(this.handlers)) delete this.handlers[key];
    }
    /** Number of handlers registered for `event`. */
    listenerCount(event) {
      return this.handlers[event]?.size ?? 0;
    }
  };

  // platform/web/p2pkit/src/framing/index.ts
  var CHUNK_LIMITS = Object.freeze({
    packetChars: 16e3,
    messageBytes: 1048576,
    fragments: 128,
    pendingGroups: 16,
    pendingBytes: 4194304,
    lifetimeMs: 15e3
  });
  var encoder = new TextEncoder();
  var Chunker = class {
    constructor(options = {}) {
      __publicField(this, "maxPacketSize");
      __publicField(this, "inbox", /* @__PURE__ */ new Map());
      __publicField(this, "bytes", 0);
      this.maxPacketSize = options.maxPacketSize ?? CHUNK_LIMITS.packetChars;
      if (!Number.isSafeInteger(this.maxPacketSize) || this.maxPacketSize < 1 || this.maxPacketSize > CHUNK_LIMITS.packetChars) throw new Error("Invalid chunk size");
    }
    *split(id, data) {
      if (!validId(id) || typeof data !== "string" || data.length > CHUNK_LIMITS.messageBytes || encoder.encode(data).length > CHUNK_LIMITS.messageBytes) throw new Error("Message too large");
      const n = Math.max(1, Math.ceil(data.length / this.maxPacketSize));
      if (n > CHUNK_LIMITS.fragments) throw new Error("Too many fragments");
      for (let i = 0; i < n; ++i) {
        yield JSON.stringify({ id, i, n, part: data.slice(i * this.maxPacketSize, (i + 1) * this.maxPacketSize) });
      }
    }
    /** Called by the transport's timer as well as on receipt, including when a peer goes silent. */
    checkDeadline(now = performance.now()) {
      for (const entry of this.inbox.values()) {
        if (now - entry.created >= CHUNK_LIMITS.lifetimeMs) throw new Error("Incomplete message expired");
      }
    }
    ingest(packet) {
      this.checkDeadline();
      if (!packet || typeof packet !== "object" || Array.isArray(packet)) throw new Error("Invalid fragment");
      const { id, i, n, part } = packet;
      if (!validId(id) || !Number.isSafeInteger(n) || n < 1 || n > CHUNK_LIMITS.fragments || !Number.isSafeInteger(i) || i < 0 || i >= n || typeof part !== "string" || part.length > this.maxPacketSize) throw new Error("Invalid fragment");
      let entry = this.inbox.get(id);
      if (entry && entry.parts.length !== n) throw new Error("Fragment count changed");
      const bytes = encoder.encode(part).length;
      if (n === 1) return part;
      if (!entry) {
        if (this.inbox.size >= CHUNK_LIMITS.pendingGroups) throw new Error("Too many incomplete messages");
        entry = { parts: new Array(n), received: 0, bytes: 0, created: performance.now() };
        this.inbox.set(id, entry);
      }
      const previous = entry.parts[i];
      if (previous !== void 0) {
        if (previous !== part) throw new Error("Conflicting fragment");
        return void 0;
      }
      if (bytes > CHUNK_LIMITS.messageBytes - entry.bytes || bytes > CHUNK_LIMITS.pendingBytes - this.bytes) {
        throw new Error("Reassembly budget exceeded");
      }
      entry.parts[i] = part;
      entry.received++;
      entry.bytes += bytes;
      this.bytes += bytes;
      if (entry.received !== n) return void 0;
      this.inbox.delete(id);
      this.bytes -= entry.bytes;
      return entry.parts.join("");
    }
    reset() {
      this.inbox.clear();
      this.bytes = 0;
    }
  };
  function validId(id) {
    return typeof id === "string" && /^[A-Za-z0-9_-]{1,64}$/.test(id);
  }

  // platform/web/p2pkit/src/utils/id.ts
  function randomId(bytes = 16) {
    const buf = new Uint8Array(bytes);
    globalThis.crypto.getRandomValues(buf);
    let out = "";
    for (const b of buf) out += b.toString(16).padStart(2, "0");
    return out;
  }

  // platform/web/p2pkit/src/utils/ice.ts
  var DEFAULT_ICE_SERVERS = [
    { urls: "stun:stun.l.google.com:19302" },
    { urls: "stun:stun1.l.google.com:19302" },
    { urls: "stun:stun2.l.google.com:19302" },
    { urls: "stun:global.stun.twilio.com:3478" }
  ];

  // platform/web/p2pkit/src/transports/rtc.ts
  var MAX_BUFFER = 1 << 20;
  var MAX_OUTGOING = 4 << 20;
  var MAX_SIGNALS = 128;
  var MAX_SDP = 65536;
  var MAX_CANDIDATE = 2048;
  var CONNECT_TIMEOUT = 3e4;
  var SEND_TIMEOUT = 1e4;
  function directIceServers(servers) {
    if (!Array.isArray(servers) || servers.length > 8) throw new Error("Invalid STUN configuration");
    return servers.map((server) => {
      const urls = typeof server.urls === "string" ? [server.urls] : server.urls;
      if (!Array.isArray(urls) || urls.length === 0 || urls.length > 8 || server.username || server.credential || urls.some((url) => typeof url !== "string" || url.length > 256 || !/^stuns?:[a-zA-Z0-9.\[\]:-]+$/.test(url))) throw new Error("Only STUN is supported for direct play");
      return { urls: [...urls] };
    });
  }
  function validateDirectCandidate(candidate) {
    if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) throw new Error("Invalid ICE candidate");
    const { candidate: value, sdpMid, sdpMLineIndex } = candidate;
    if (typeof value !== "string" || value.length > MAX_CANDIDATE || /[\r\n\0]/.test(value) || value !== "" && (!value.startsWith("candidate:") || /\styp\s+relay(?:\s|$)/.test(value) || !/\styp (host|srflx|prflx)(?:\s|$)/.test(value)) || sdpMid !== void 0 && sdpMid !== null && (typeof sdpMid !== "string" || !/^[A-Za-z0-9_-]{1,64}$/.test(sdpMid)) || sdpMLineIndex !== void 0 && sdpMLineIndex !== null && (!Number.isInteger(sdpMLineIndex) || sdpMLineIndex < 0 || sdpMLineIndex > 16)) throw new Error("Invalid direct ICE candidate");
  }
  function validateDirectDescription(description) {
    if (!description || typeof description !== "object") throw new Error("Invalid session description");
    const { type, sdp } = description;
    if (type !== "offer" && type !== "answer" || typeof sdp !== "string" || sdp.length > MAX_SDP || sdp.includes("\0") || !/^v=0\r?\n/.test(sdp) || !/^a=fingerprint:sha-256 (?:[0-9A-Fa-f]{2}:){31}[0-9A-Fa-f]{2}\r?$/m.test(sdp) || (sdp.match(/^a=fingerprint:/gm)?.length ?? 0) !== 1 || (sdp.match(/^m=application /gm)?.length ?? 0) !== 1 || /^m=(?!application )/m.test(sdp)) throw new Error("Invalid data-channel description");
    let count = 0;
    for (const line of sdp.split(/\r?\n/)) {
      if (line.startsWith("a=candidate:")) {
        if (++count > MAX_SIGNALS) throw new Error("Too many ICE candidates");
        validateDirectCandidate({ candidate: line.slice(2) });
      }
    }
  }
  var RTCTransport = class {
    constructor(options) {
      __publicField(this, "remote");
      __publicField(this, "name", "rtc");
      __publicField(this, "self");
      __publicField(this, "signalling");
      __publicField(this, "emitter", new Emitter());
      __publicField(this, "chunker");
      __publicField(this, "pc");
      __publicField(this, "initiator");
      __publicField(this, "label");
      __publicField(this, "channel");
      __publicField(this, "remoteDescriptionSet", false);
      __publicField(this, "pendingCandidates", []);
      __publicField(this, "signalChain", Promise.resolve());
      __publicField(this, "signalCount", 0);
      __publicField(this, "candidateCount", 0);
      __publicField(this, "sendQueue", []);
      __publicField(this, "sendTimer");
      __publicField(this, "outgoingBytes", 0);
      __publicField(this, "outgoingCount", 0);
      __publicField(this, "closed", false);
      __publicField(this, "opened", false);
      __publicField(this, "trafficStart", performance.now());
      __publicField(this, "trafficPackets", 0);
      __publicField(this, "trafficBytes", 0);
      __publicField(this, "started", performance.now());
      __publicField(this, "timer");
      __publicField(this, "unsubscribe");
      __publicField(this, "onSignal", (message) => {
        if (this.closed || !message || typeof message !== "object" || !("to" in message) || message.from !== this.remote || message.to !== this.self) return;
        if (++this.signalCount > MAX_SIGNALS) {
          this.signalCount--;
          this.fail("Too many connection messages");
          return;
        }
        this.signalChain = this.signalChain.then(() => this.handleSignal(message)).catch(() => this.fail("Invalid direct connection details")).finally(() => {
          this.signalCount--;
        });
      });
      this.self = options.self;
      this.remote = options.remote;
      this.signalling = options.signalling;
      this.initiator = options.initiator;
      this.label = options.label ?? "p2pkit";
      this.chunker = new Chunker({ maxPacketSize: options.chunkSize });
      this.pc = new options.backend.RTCPeerConnection({ iceServers: directIceServers(options.iceServers ?? DEFAULT_ICE_SERVERS) });
      this.pc.onicecandidate = (ev) => {
        if (this.closed || !ev.candidate) return;
        try {
          const candidate = ev.candidate.toJSON();
          validateDirectCandidate(candidate);
          if (candidate.candidate === "") return;
          this.signalling.send({ iceCandidate: candidate, from: this.self, to: this.remote });
        } catch {
          this.fail("Could not exchange direct connection details");
        }
      };
      this.pc.onconnectionstatechange = () => {
        if (["failed", "closed", "disconnected"].includes(this.pc.connectionState)) this.disconnect();
      };
      const unsubscribe = this.signalling.onMessage(this.onSignal);
      if (typeof unsubscribe === "function") this.unsubscribe = unsubscribe;
      this.timer = setInterval(() => {
        try {
          if (!this.opened && performance.now() - this.started > CONNECT_TIMEOUT) {
            this.fail("Could not connect directly. This network may block peer-to-peer connections.");
          }
          this.chunker.checkDeadline();
        } catch {
          this.fail("A peer sent an incomplete message");
        }
      }, 1e3);
      this.timer.unref?.();
      if (this.initiator) {
        this.setupChannel(this.pc.createDataChannel(this.label, { ordered: true }));
        void this.negotiate().catch(() => this.fail("Direct connection negotiation failed"));
      } else this.pc.ondatachannel = (ev) => this.setupChannel(ev.channel);
    }
    get bufferedAmount() {
      return this.outgoingBytes + (this.channel?.bufferedAmount ?? 0);
    }
    on(event, handler) {
      this.emitter.on(event, handler);
    }
    send(value) {
      return new Promise((resolve, reject) => {
        if (!this.enqueue(value, resolve, reject)) reject(new Error("Direct send was refused"));
      });
    }
    /** True means accepted by this bounded queue, never a promise masquerading as success. */
    trySend(value) {
      return this.enqueue(value, () => {
      }, () => {
      });
    }
    enqueue(value, resolve, reject) {
      if (this.closed || !this.opened || this.channel?.readyState !== "open") return false;
      try {
        const data = JSON.stringify(value);
        if (typeof data !== "string" || data.length > CHUNK_LIMITS.messageBytes) return false;
        const bytes = new TextEncoder().encode(data).length;
        if (bytes > CHUNK_LIMITS.messageBytes || bytes > MAX_OUTGOING - this.outgoingBytes || this.outgoingCount >= 128) {
          this.fail("Direct connection send queue is full");
          return false;
        }
        this.sendQueue.push({
          packets: [...this.chunker.split(randomId(8), data)],
          next: 0,
          bytes,
          deadline: performance.now() + SEND_TIMEOUT,
          resolve,
          reject
        });
        this.outgoingBytes += bytes;
        this.outgoingCount++;
        this.drainSends();
        return !this.closed;
      } catch {
        this.fail("Direct connection could not deliver a message");
        return false;
      }
    }
    drainSends() {
      if (this.sendTimer !== void 0) {
        clearTimeout(this.sendTimer);
        this.sendTimer = void 0;
      }
      try {
        while (!this.closed && this.sendQueue.length) {
          const job = this.sendQueue[0], channel = this.channel;
          if (channel?.readyState !== "open") throw new Error("Direct channel closed");
          if (performance.now() > job.deadline) throw new Error("Direct channel stalled");
          while (job.next < job.packets.length) {
            if (channel.bufferedAmount > MAX_BUFFER) {
              this.sendTimer = setTimeout(() => this.drainSends(), 10);
              return;
            }
            channel.send(job.packets[job.next++]);
          }
          this.sendQueue.shift();
          this.outgoingBytes -= job.bytes;
          this.outgoingCount--;
          job.resolve();
        }
      } catch {
        this.fail("Direct connection could not deliver a message");
      }
    }
    disconnect() {
      if (this.closed) return;
      this.closed = true;
      clearInterval(this.timer);
      if (this.sendTimer !== void 0) clearTimeout(this.sendTimer);
      for (const job of this.sendQueue.splice(0)) job.reject(new Error("Direct connection closed"));
      this.outgoingBytes = 0;
      this.outgoingCount = 0;
      this.unsubscribe?.();
      this.pendingCandidates.length = 0;
      this.chunker.reset();
      this.pc.onicecandidate = null;
      this.pc.ondatachannel = null;
      this.pc.onconnectionstatechange = null;
      try {
        this.channel?.close();
      } catch {
      }
      try {
        this.pc.close();
      } catch {
      }
      this.emitter.emit("disconnect");
    }
    fail(message) {
      if (this.closed) return;
      try {
        this.emitter.emit("error", new Error(message));
      } finally {
        this.disconnect();
      }
    }
    async negotiate() {
      await this.signalling.ready;
      if (this.closed) return;
      const offer = await this.pc.createOffer();
      if (this.closed) return;
      await this.pc.setLocalDescription(offer);
      this.sendDescription();
    }
    sendDescription() {
      if (this.closed) return;
      const description = this.pc.localDescription;
      if (!description) throw new Error("Missing local description");
      validateDirectDescription(description);
      this.signalling.send({ description: { type: description.type, sdp: description.sdp }, from: this.self, to: this.remote });
    }
    async handleSignal(message) {
      if (this.closed) return;
      if ("description" in message) {
        validateDirectDescription(message.description);
        if (this.remoteDescriptionSet || message.description.type !== (this.initiator ? "answer" : "offer")) throw new Error("Unexpected description");
        await this.pc.setRemoteDescription(message.description);
        if (this.closed) return;
        this.remoteDescriptionSet = true;
        for (const candidate of this.pendingCandidates.splice(0)) {
          await this.pc.addIceCandidate(candidate);
          if (this.closed) return;
        }
        if (!this.initiator) {
          const answer = await this.pc.createAnswer();
          if (this.closed) return;
          await this.pc.setLocalDescription(answer);
          this.sendDescription();
        }
      } else if ("iceCandidate" in message) {
        validateDirectCandidate(message.iceCandidate);
        if (++this.candidateCount > MAX_SIGNALS) throw new Error("Too many candidates");
        if (this.remoteDescriptionSet) await this.pc.addIceCandidate(message.iceCandidate);
        else this.pendingCandidates.push(message.iceCandidate);
      } else throw new Error("Unexpected connection message");
    }
    setupChannel(channel) {
      if (this.closed || this.channel || channel.label !== this.label || !channel.ordered || channel.maxRetransmits !== null || channel.maxPacketLifeTime !== null) {
        channel.close();
        this.fail("Invalid direct game channel");
        return;
      }
      this.channel = channel;
      channel.binaryType = "arraybuffer";
      channel.onopen = () => {
        if (this.closed || this.opened) return;
        this.opened = true;
        this.emitter.emit("connect");
      };
      channel.onmessage = (ev) => this.onData(ev.data);
      channel.onclose = () => this.disconnect();
      channel.onerror = () => this.fail("Direct game channel failed");
      if (channel.readyState === "open") queueMicrotask(() => channel.onopen?.(new Event("open")));
    }
    onData(data) {
      if (this.closed || !this.opened) return;
      try {
        if (typeof data !== "string" && !(data instanceof ArrayBuffer) || (typeof data === "string" ? data.length : data.byteLength) > 131072) throw new Error("Oversized fragment");
        const raw = typeof data === "string" ? data : new TextDecoder("utf-8", { fatal: true }).decode(data);
        const now = performance.now();
        if (now - this.trafficStart >= 1e3) {
          this.trafficStart = now;
          this.trafficPackets = 0;
          this.trafficBytes = 0;
        }
        const bytes = typeof data === "string" ? new TextEncoder().encode(raw).length : data.byteLength;
        this.trafficPackets++;
        this.trafficBytes += bytes;
        if (this.trafficPackets > 4096 || this.trafficBytes > 16 * 1024 * 1024) throw new Error("Peer traffic limit exceeded");
        const full = this.chunker.ingest(JSON.parse(raw));
        if (full !== void 0) this.emitter.emit("message", JSON.parse(full));
      } catch {
        this.fail("A peer sent an invalid game frame");
      }
    }
  };

  // platform/web/src/dune-direct-bridge.ts
  var State = { New: 0, Connecting: 1, Connected: 2, Failed: 3, Closed: 4 };
  var MAX_QUEUED_VALUES = 4096;
  var MAX_QUEUED_VALUE_BYTES = 4 * 1024 * 1024;
  var MAX_QUEUED_SIGNALS = 256;
  var MAX_SIGNAL_CHARS = 65536;
  var connections = /* @__PURE__ */ new Map();
  var nextHandle = 1;
  function encodeCandidate(candidate) {
    return `${candidate.sdpMid || "0"}|${candidate.candidate}`;
  }
  function decodeCandidate(payload) {
    const split = payload.indexOf("|");
    if (split < 0) return null;
    const sdpMid = payload.slice(0, split);
    const candidate = payload.slice(split + 1);
    if (!candidate || candidate.length > MAX_SIGNAL_CHARS) return null;
    return { candidate, sdpMid };
  }
  function fail(connection, reason) {
    if (connection.state !== State.Closed) connection.state = State.Failed;
    if (!connection.error) connection.error = reason;
    connection.values.length = 0;
    connection.valueBytes = 0;
    connection.signals.length = 0;
    try {
      connection.transport?.disconnect();
    } catch {
    }
  }
  function usable(connection) {
    return connection !== void 0 && connection.state !== State.Failed && connection.state !== State.Closed && connection.deliver !== null;
  }
  function parseIceServers(iceServersJson) {
    let parsed;
    try {
      parsed = JSON.parse(iceServersJson);
    } catch {
      return null;
    }
    if (!Array.isArray(parsed) || parsed.length > 4) return null;
    const servers = [];
    for (const url of parsed) {
      if (typeof url !== "string" || !/^stuns?:[a-zA-Z0-9.\[\]:-]+$/.test(url)) return null;
      servers.push({ urls: url });
    }
    return servers;
  }
  function create(iceServersJson, initiator, label) {
    const iceServers = parseIceServers(iceServersJson);
    if (iceServers === null) return 0;
    const handle = nextHandle++;
    let resolveReady = () => {
    };
    const ready = new Promise((resolve) => {
      resolveReady = resolve;
    });
    const connection = {
      transport: void 0,
      deliver: null,
      ready: resolveReady,
      signals: [],
      values: [],
      valueBytes: 0,
      state: State.New,
      error: ""
    };
    const signalling = {
      ready,
      send(message) {
        if (connection.signals.length >= MAX_QUEUED_SIGNALS) {
          fail(connection, "local signal queue overflowed");
          return;
        }
        if ("description" in message) {
          const sdp = message.description.sdp ?? "";
          if (sdp.length > MAX_SIGNAL_CHARS) {
            fail(connection, "local description too large");
            return;
          }
          connection.signals.push(`${message.description.type === "answer" ? "answer" : "offer"}|${sdp}`);
        } else if ("iceCandidate" in message) {
          connection.signals.push(`candidate|${encodeCandidate(message.iceCandidate)}`);
        }
      },
      onMessage(handler) {
        connection.deliver = handler;
        return () => {
          if (connection.deliver === handler) connection.deliver = null;
        };
      }
    };
    connection.transport = new RTCTransport({
      self: "local",
      remote: "remote",
      signalling,
      backend: { RTCPeerConnection: globalThis.RTCPeerConnection },
      // Exactly the servers the signaling service named, and no others. An empty list means host
      // candidates only, which is the right answer on a LAN; falling back to P2PKit's public STUN
      // defaults would contact a third party this game never told the player about.
      iceServers,
      initiator,
      label
    });
    connection.transport.on("connect", () => {
      if (connection.state !== State.Failed && connection.state !== State.Closed) {
        connection.state = State.Connected;
      }
    });
    connection.transport.on("message", (value) => {
      if (connection.state === State.Failed || connection.state === State.Closed) return;
      if (typeof value !== "string") {
        fail(connection, "peer sent a non-string payload");
        return;
      }
      if (connection.values.length >= MAX_QUEUED_VALUES || connection.valueBytes + value.length > MAX_QUEUED_VALUE_BYTES) {
        fail(connection, "this computer could not keep up with a player's messages");
        return;
      }
      connection.valueBytes += value.length;
      connection.values.push(value);
    });
    connection.transport.on("disconnect", () => {
      if (connection.state !== State.Failed) connection.state = State.Closed;
    });
    connection.transport.on("error", (error) => {
      fail(connection, error instanceof Error ? error.message : "data channel error");
    });
    resolveReady();
    connection.state = State.Connecting;
    connections.set(handle, connection);
    return handle;
  }
  var bridge = {
    create,
    /** Applies a remote offer or answer. The C++ side has already checked the fingerprint. */
    setRemoteDescription(handle, kind, sdp) {
      const connection = connections.get(handle);
      if (!usable(connection) || sdp.length > MAX_SIGNAL_CHARS) return false;
      connection.deliver({
        description: { type: kind === "answer" ? "answer" : "offer", sdp },
        from: "remote",
        to: "local"
      });
      return true;
    },
    addRemoteCandidate(handle, payload) {
      const connection = connections.get(handle);
      if (!usable(connection)) return false;
      const candidate = decodeCandidate(payload);
      if (!candidate) return false;
      connection.deliver({ iceCandidate: candidate, from: "remote", to: "local" });
      return true;
    },
    /** Sends one envelope. The text is a JSON value; RTCTransport fragments it. */
    sendValue(handle, text) {
      const connection = connections.get(handle);
      if (!connection || connection.state !== State.Connected) return false;
      if (connection.transport.bufferedAmount > 4 * 1024 * 1024) return false;
      let value;
      try {
        value = JSON.parse(text);
      } catch {
        return false;
      }
      if (typeof value !== "string") return false;
      return connection.transport.trySend(value);
    },
    /** Takes one received envelope as JSON text, or null. */
    pollValue(handle) {
      const connection = connections.get(handle);
      if (!connection || connection.values.length === 0) return null;
      const value = connection.values.shift();
      connection.valueBytes -= value.length;
      return JSON.stringify(value);
    },
    /** Takes one locally produced signal as "<kind>|<payload>", or null. */
    pollSignal(handle) {
      const connection = connections.get(handle);
      if (!connection || connection.signals.length === 0) return null;
      return connection.signals.shift();
    },
    bufferedAmount(handle) {
      const connection = connections.get(handle);
      return connection ? connection.transport.bufferedAmount : 0;
    },
    state(handle) {
      const connection = connections.get(handle);
      return connection ? connection.state : State.Closed;
    },
    lastError(handle) {
      const connection = connections.get(handle);
      return connection ? connection.error : "";
    },
    close(handle) {
      const connection = connections.get(handle);
      if (!connection) return;
      try {
        connection.transport.disconnect();
      } catch {
      }
      connection.state = State.Closed;
      connection.values.length = 0;
      connection.signals.length = 0;
      connections.delete(handle);
    }
  };
  globalThis.DuneDirectBridge = bridge;
  var dune_direct_bridge_default = bridge;
})();
