
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:4 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/opt/homebrew/bin/"
      - "/Users/stefanclaw/development/hermes-agent/venv/bin/"
    searched_directories:
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/opt/homebrew/bin"
        - "/Users/stefanclaw/development/hermes-agent/venv/bin"
...

---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/Users/stefanclaw/dune/dunelegacy/vcpkg/scripts/buildsystems/vcpkg.cmake:309 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:146 (include)"
      - "CMakeLists.txt:4 (project)"
    mode: "program"
    variable: "Z_VCPKG_CL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "cl"
    candidate_directories:
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/opt/homebrew/bin/"
      - "/Users/stefanclaw/development/hermes-agent/venv/bin/"
    searched_directories:
      - "/usr/local/bin/cl"
      - "/System/Cryptexes/App/usr/bin/cl"
      - "/usr/bin/cl"
      - "/bin/cl"
      - "/usr/sbin/cl"
      - "/sbin/cl"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/cl"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/cl"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/cl"
      - "/opt/pmk/env/global/bin/cl"
      - "/opt/homebrew/bin/cl"
      - "/Users/stefanclaw/development/hermes-agent/venv/bin/cl"
    found: false
    search_context:
      ENV{PATH}:
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/opt/homebrew/bin"
        - "/Users/stefanclaw/development/hermes-agent/venv/bin"
...
