import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('../../', import.meta.url));
await build({
  entryPoints: [path.join(root, 'platform/web/src/dune-direct-bridge.ts')],
  outfile: path.join(root, 'platform/web/p2p-direct.js'),
  bundle: true, format: 'iife', platform: 'browser', target: ['es2020'],
  minify: false, legalComments: 'inline', sourcemap: false,
  banner: {js: '// DuneCity direct transport. P2PKit 94ae7eb8818a629478e0a6ba0aa3232c5fc0b1ab (MIT); local security patches. Generated by tools/p2pkit-build/build.mjs.'},
});
